//Movies
export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const ERROR_RECEIVE_MOVIES = 'ERROR_RECEIVE_MOVIES';

export const REQUEST_DELETE_MOVIE = 'REQUEST_DELETE_MOVIE';
export const SUCCESS_DELETE_MOVIE = 'SUCCESS_DELETED_MOVIE';
export const ERROR_DELETE_MOVIE = 'ERROR_DELETE_MOVIE';

export const REQUEST_FILTER_MOVIES = 'REQUEST_FILTER_MOVIES';
export const SUCCESS_FILTER_MOVIES = 'SUCCESS_FILTER_MOVIES';
export const ERROR_FILTER_MOVIES = 'ERROR_FILTER_MOVIES';

export const UPDATE_MOVIES = 'UPDATE_MOVIES';
