//Movie
export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const ERROR_RECEIVE_MOVIE = 'ERROR_RECEIVE_MOVIE';

export const REQUEST_UPDATE_MOVIE = 'REQUEST_UPDATE_MOVIE';
export const SUCCESS_UPDATE_MOVIE = 'SUCCESS_UPDATE_MOVIE';
export const ERROR_UPDATE_MOVIE = 'ERROR_UPDATE_MOVIE';
